[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Clink-arg=/MD"]

[target.aarch64-unknown-linux-musl]
rustflags = [
	#"-C", "link-arg=-fuse-ld=aarch64-linux-gnu-ld",
	"-C", "linker=aarch64-linux-gnu-ld",
]
